name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Make sure this matches the Node version in your project

      - name: Install dependencies
        run: npm install

      - name: Run build (optional)
        run: npm run build  # Make sure you have a "build" script in package.json

      - name: Run tests (optional)
        run: npm test  # If you have a test script set up
