name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust version if needed

      - name: Install dependencies
        run: npm install

      - name: Run build (optional)
        run: npm run build

      # Remove or comment out this block if you don't need tests
      # - name: Run tests (optional)
      #   run: npm test
